# sentdex: bare calculations

In [1]:
inputs = [1., 2., 3.]
weights = [0.2, 0.8, -0.5]
bias = 2.0

output = inputs[0]*weights[0] + inputs[1]*weights[1] + inputs[2]*weights[2] + bias 

print(output)

2.3


In [2]:
inputs = [1., 5., 3., 2.5]

weights1 = [0.2, 0.8, -0.5, 1.0]
weights2 = [0.5, -0.91, 0.26, -0.5]
weights3 = [-0.26, -0.27, 0.17, 0.87]

bias1 = 2.0
bias2 = 3.0
bias3 = 0.5

output = ([
    inputs[0]*weights1[0] + inputs[1]*weights1[1] + inputs[2]*weights1[2] + inputs[3]*weights1[3] + bias1, 
    inputs[0]*weights2[0] + inputs[1]*weights2[1] + inputs[2]*weights2[2] + inputs[3]*weights2[3] + bias2, 
    inputs[0]*weights3[0] + inputs[1]*weights3[1] + inputs[2]*weights3[2] + inputs[3]*weights3[3] + bias3
])

output

[7.2, -1.5199999999999996, 1.5749999999999997]

# hopez: calculation via numpy array

In [3]:
import numpy as np

inputs_arr_1d = np.array([1., 5., 3., 2.5])

weights_arr_2d = np.array([
    [0.2, 0.8, -0.5, 1.0], 
    [0.5, -0.91, 0.26, -0.5],
    [-0.26, -0.27, 0.17, 0.87]
])

bias_arr_1d = np.array([2.0, 3.0, 0.5])

print('input arr_1d')
print(inputs_arr_1d, '\n')
print('weights arr_2d')
print(weights_arr_2d, '\n')
print('bias arr_1d')
print(bias_arr_1d, '\n')

input arr_1d
[1.  5.  3.  2.5] 

weights arr_2d
[[ 0.2   0.8  -0.5   1.  ]
 [ 0.5  -0.91  0.26 -0.5 ]
 [-0.26 -0.27  0.17  0.87]] 

bias arr_1d
[2.  3.  0.5] 



# hopez: calculation via numpy array

In [4]:
inputs_arr_2d = np.tile(inputs_arr_1d, (3, 1))
inputs_arr_2d

array([[1. , 5. , 3. , 2.5],
       [1. , 5. , 3. , 2.5],
       [1. , 5. , 3. , 2.5]])

In [5]:
inputs_x_weights = np.multiply(inputs_arr_2d, weights_arr_2d)
inputs_x_weights 

array([[ 0.2  ,  4.   , -1.5  ,  2.5  ],
       [ 0.5  , -4.55 ,  0.78 , -1.25 ],
       [-0.26 , -1.35 ,  0.51 ,  2.175]])

In [6]:
sum_inputs_x_weights = np.sum(inputs_x_weights, axis=1)
sum_inputs_x_weights

array([ 5.2  , -4.52 ,  1.075])

In [7]:
output2 = np.add(sum_inputs_x_weights, bias_arr_1d)
output2

array([ 7.2  , -1.52 ,  1.575])

In [8]:
type(output2)

numpy.ndarray